import re, os, sys

SRC = r"E:/Unreal/Projects/_TEST/FluidTest/Docs/tmp.txt"
OUT = r"E:/Unreal/Projects/_TEST/FluidTest/Docs/tmp_extracted.md"

text = open(SRC, encoding="utf-8").read()
lines = text.split("\n")

# ---- block split ----
blocks = []
cur = None
for ln in lines:
    if ln.startswith("Begin Object"):
        cur = {"raw": [ln]}
    elif ln.startswith("End Object"):
        if cur is not None:
            cur["raw"].append(ln)
            blocks.append(cur)
            cur = None
    elif cur is not None:
        cur["raw"].append(ln)

CLASS_SHORT = {
    "K2Node_Tunnel": "Tunnel",
    "EdGraphNode_Comment": "Comment",
    "K2Node_VariableSet": "Set",
    "K2Node_VariableGet": "Get",
    "K2Node_IfThenElse": "Branch",
    "K2Node_CallFunction": "Call",
    "K2Node_Knot": "Knot",
    "K2Node_CommutativeAssociativeBinaryOperator": "LogicOp",
    "K2Node_CallArrayFunction": "ArrayCall",
    "K2Node_PromotableOperator": "Op",
    "K2Node_DynamicCast": "Cast",
}

nodes = []          # list of dicts
pinid_map = {}      # PinId -> (node_name, pin_name)

begin_re = re.compile(r'Begin Object Class=/Script/[\w.]+?\.(\w+) Name="([^"]+)"')
guid_re = re.compile(r'NodeGuid=([0-9A-F]{32})')
pos_re = re.compile(r'NodePosX=(-?\d+)\s+NodePosY=(-?\d+)')
varref_re = re.compile(r'VariableReference=\((.*?)\)')
funcref_re = re.compile(r'FunctionReference=\((.*?)\)')
targettype_re = re.compile(r'TargetType="([^"]+)"')
opname_re = re.compile(r'OperationName="([^"]+)"')
nodecomment_re = re.compile(r'NodeComment="(.*?)"', re.S)
# line-anchored: capture the FULL pin content up to the line's final ')'
# (pin lines contain nested '()' from PinType fields; greedy . without re.S = whole line)
pin_re = re.compile(r'^\s*CustomProperties Pin \((.*)\)\s*$', re.M)
userpin_re = re.compile(r'^\s*CustomProperties UserDefinedPin \((.*)\)\s*$', re.M)

def parse_kv(s):
    """parse a (...) inner content into key->value tokens (value may be quoted/bracketed)."""
    out = {}
    # tokenize by top-level commas
    depth = 0; cur = ""; parts = []
    for ch in s:
        if ch == '(':
            depth += 1; cur += ch
        elif ch == ')':
            depth -= 1; cur += ch
        elif ch == ',' and depth == 0:
            parts.append(cur); cur = ""
        else:
            cur += ch
    if cur.strip():
        parts.append(cur)
    for p in parts:
        p = p.strip()
        m = re.match(r'(\w+)=(.*)', p)
        if m:
            out[m.group(1)] = m.group(2).strip()
    return out

for b in blocks:
    raw = "\n".join(b["raw"])
    m = begin_re.search(b["raw"][0])
    cls = m.group(1); name = m.group(2)
    node = {
        "class": cls, "short": CLASS_SHORT.get(cls, cls),
        "name": name, "guid": None, "pos": None,
        "varref": None, "funcref": None, "targettype": None,
        "opname": None, "nodecomment": None, "pins": [], "userpins": [],
        "comment_text": None,
    }
    g = guid_re.search(raw); node["guid"] = g.group(1) if g else None
    p = pos_re.search(raw)
    if p: node["pos"] = (int(p.group(1)), int(p.group(2)))
    # VariableReference / FunctionReference
    for key, store in (("VariableReference", "varref"), ("FunctionReference", "funcref")):
        mm = re.search(key + r'=\((.*?)\)', raw)
        if mm:
            kv = parse_kv(mm.group(1))
            node[store] = kv
    tt = targettype_re.search(raw); node["targettype"] = tt.group(1) if tt else None
    op = opname_re.search(raw); node["opname"] = op.group(1) if op else None
    nc = nodecomment_re.search(raw); node["nodecomment"] = nc.group(1).replace("\\r\\n"," ").strip() if nc else None
    # comment node text
    if cls == "EdGraphNode_Comment":
        cm = re.search(r'NodeComment="(.*?)"', raw, re.S)
        if cm: node["comment_text"] = cm.group(1).replace("\\r\\n"," ").strip()
    # pins
    for pm in pin_re.finditer(raw):
        kv = parse_kv(pm.group(1))
        pin = {
            "pinid": kv.get("PinId"),
            "pinname": kv.get("PinName"),
            "dir": kv.get("Direction"),
            "cat": None, "default": None, "autogen": None, "linked": [],
        }
        # category from PinType.PinCategory="..."
        pcat = re.search(r'PinType\.PinCategory="([^"]*)"', pm.group(1))
        if pcat: pin["cat"] = pcat.group(1)
        if "DefaultValue" in kv: pin["default"] = kv["DefaultValue"]
        if "AutogeneratedDefaultValue" in kv: pin["autogen"] = kv["AutogeneratedDefaultValue"]
        lt = re.search(r'LinkedTo=\(([^)]*)\)', pm.group(1))
        if lt and lt.group(1).strip():
            for ent in lt.group(1).split(','):
                ent = ent.strip()
                if not ent: continue
                mm2 = re.match(r'(\w+)\s+([0-9A-F]+)', ent)
                if mm2: pin["linked"].append((mm2.group(1), mm2.group(2)))
        if pin["pinid"]:
            pinid_map[pin["pinid"]] = (name, pin["pinname"])
        node["pins"].append(pin)
    for up in userpin_re.finditer(raw):
        kv = parse_kv(up.group(1))
        node["userpins"].append(kv)
    nodes.append(node)

# resolve linked targets to (node, pinname)
for n in nodes:
    for pin in n["pins"]:
        pin["resolved"] = []
        for (nn, pid) in pin["linked"]:
            if pid in pinid_map:
                pin["resolved"].append(pinid_map[pid])
            else:
                pin["resolved"].append((nn, pid))

# ---- decide which pins to emit ----
def is_self_pin(pin):
    return pin["pinname"] == "self"

def meaningful_default(pin):
    if pin["default"] is None: return False
    if pin["autogen"] is None: return True  # literal constant (no autogen)
    return pin["default"] != pin["autogen"]

def emit_pin(pin):
    if is_self_pin(pin):
        return bool(pin["resolved"])  # keep only if wired
    if pin["cat"] == "exec":
        return True  # exec flow always relevant
    if pin["resolved"]:
        return True
    if meaningful_default(pin):
        return True
    return False

# ---- build output ----
out = []
out.append("# 蓝图功能提取（压缩版） / Blueprint Functional Extract")
out.append("")
out.append("- 源文件: `Docs/tmp.txt`")
# graph name
gm = re.search(r'K2Node_Composite_\d+\.([\w-]+)\.', text)
if gm: out.append("- 子图(Composite): `%s`" % gm.group(1))
out.append("- 节点总数: %d  （类型 %d 种）" % (len(nodes), len(set(n["class"] for n in nodes))))
orig_size = os.path.getsize(SRC)
out.append("- 原始大小: %.1f KB / %d 行" % (orig_size/1024, len(lines)))

# comment section
comments = [n for n in nodes if n["class"] == "EdGraphNode_Comment" and n["comment_text"]]
if comments:
    out.append("")
    out.append("## 设计注释（Comment 节点，原样保留）")
    for n in comments:
        t = n["comment_text"]
        out.append("- **[%s]** %s" % (n["name"], t))
        out.append("")

# derived tables
sets = [n for n in nodes if n["class"] == "K2Node_VariableSet"]
gets = [n for n in nodes if n["class"] == "K2Node_VariableGet"]
calls = [n for n in nodes if n["class"] in ("K2Node_CallFunction","K2Node_CallArrayFunction")]
casts = [n for n in nodes if n["class"] == "K2Node_DynamicCast"]
ops = [n for n in nodes if n["class"] in ("K2Node_CommutativeAssociativeBinaryOperator","K2Node_PromotableOperator")]

def ref_str(kv):
    if not kv: return "?"
    mn = kv.get("MemberName","?")
    if kv.get("bSelfContext") == "True":
        return "%s (self)" % mn
    mp = kv.get("MemberParent")
    if mp:
        # strip path
        mm = re.search(r"\.(\w+)'", mp)
        clsname = mm.group(1) if mm else mp
        return "%s.%s" % (clsname, mn)
    return mn

out.append("## 派生速查表（用于 C++ 迁移）")
out.append("")
out.append("### 写入的变量 (VariableSet) — %d" % len(sets))
for n in sets:
    vr = n["varref"]
    out.append("- `%s`  (guid %s)" % (ref_str(vr), n["guid"][:8]))
out.append("")
out.append("### 读取的变量 (VariableGet) — %d" % len(gets))
for n in gets:
    out.append("- `%s`" % ref_str(n["varref"]))
out.append("")
out.append("### 调用的函数 (Call/ArrayCall) — %d" % len(calls))
for n in calls:
    out.append("- `%s`" % ref_str(n["funcref"]))
out.append("")
out.append("### 类型转换 (DynamicCast) — %d" % len(casts))
for n in casts:
    tt = n["targettype"]
    mm = re.search(r"\.([A-Za-z0-9_]+)'$", tt) if tt else None
    out.append("- → `%s`" % (mm.group(1) if mm else tt))
out.append("")
out.append("### 逻辑/数学运算 — %d" % len(ops))
for n in ops:
    op = n["opname"] or (n["funcref"] or {}).get("MemberName","?")
    out.append("- `%s` (%s)" % (op, n["short"]))
out.append("")

# node-by-node compact
out.append("## 节点图（保留全部连接/常量/条件）")
out.append("")
out.append("> 标记说明: `→` 表示 Pin 连线目标(节点.引脚)；`=` 表示字面常量；`exec`=执行流；`obj`=对象；`bool/int/string/byte/name`=数据类型")
out.append("")

for n in nodes:
    if n["class"] == "EdGraphNode_Comment":
        continue  # already listed above
    header = "### %s  [%s]" % (n["name"], n["short"])
    if n["pos"]:
        header += "  pos=%d,%d" % n["pos"]
    out.append(header)
    # semantic payload
    if n["class"] in ("K2Node_CallFunction","K2Node_CallArrayFunction"):
        out.append("- fn: `%s`" % ref_str(n["funcref"]))
    elif n["class"] in ("K2Node_VariableSet","K2Node_VariableGet"):
        out.append("- var: `%s`" % ref_str(n["varref"]))
    elif n["class"] == "K2Node_DynamicCast":
        tt = n["targettype"]; mm = re.search(r"\.([A-Za-z0-9_]+)'$", tt) if tt else None
        out.append("- cast → `%s`" % (mm.group(1) if mm else tt))
    elif n["class"] in ("K2Node_CommutativeAssociativeBinaryOperator","K2Node_PromotableOperator"):
        op = n["opname"] or (n["funcref"] or {}).get("MemberName","?")
        out.append("- op: `%s`" % op)
    if n["nodecomment"]:
        out.append("- note: %s" % n["nodecomment"])
    # pins
    for pin in n["pins"]:
        if not emit_pin(pin):
            continue
        pn = pin["pinname"]; cat = pin["cat"] or ""
        dirn = ""
        if pin["dir"] == "EGPD_Output": dirn = "⟂out"
        elif pin["dir"] == "EGPD_Input": dirn = "⟂in"
        line = "  - `%s`" % pn
        if cat and cat != "exec":
            line += " (%s)" % cat
        elif cat == "exec":
            line += " (exec)"
        if pin["resolved"]:
            targets = ", ".join("%s.%s" % (t[0], t[1]) for t in pin["resolved"])
            line += " → %s" % targets
        if meaningful_default(pin) and not pin["resolved"]:
            line += " = `%s`" % pin["default"]
        out.append(line)
    out.append("")

content = "\n".join(out)
open(OUT, "w", encoding="utf-8").write(content)
new_size = os.path.getsize(OUT)
out.append("")
print("original: %d bytes, %d lines" % (orig_size, len(lines)))
print("compact : %d bytes, %d lines" % (new_size, len(out)))
print("reduction: %.1f%% size, %.1f%% lines" % ((1-new_size/orig_size)*100, (1-len(out)/len(lines))*100))
print("nodes: %d" % len(nodes))
print("wrote", OUT)
